### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by teamb58** [Evolution-X/vendor_evolution#14]
Hi team,
I am facing this strange issue while trying to bringup on an unofficial device(Fairphone FP3). The device tree is from LineageOS with slight modification(lineage->aosp, use of evolution/configs/common_full_phone.mk). This is:
```
FAILED: /Evolution/out/soong/build.ninja
/Evolution/out/soong/.bootstrap/bin/soong_build -t -l /Evolution/out/.module_paths/Android.bp.list -b /Evolution/out/soong -n /Evolution/out -d /Evolution/out/soong/build.ninja.d -globFile /Evolution/out/soong/.bootstrap/build-globs.ninja -o /Evolution/out/soong/build.ninja Android.bp
error: vendor/evolution/build/soong/Android.bp:24:8: module "generated_kernel_includes": cmd: unknown variable '$(PATH_OVERRIDE_SOONG)'
16:59:28 soong bootstrap failed with: exit status 1

#### failed to build some targets (24:21 (mm:ss)) ####
```
Is there anything from device tree side that has to be done?

**Comment by teamb58** [comment]
@Stallix , @martonlederer @RealAkito awaiting your response. Would be glad if you can help me.

**Comment by RealAkito** [comment]
Please seek help in support@evolution-x.org

Thank you.
