### ISSUE TITLE
Roboto font choice text displays in current font instead of Roboto font

### ISSUE THREAD

**Issue by penguin-grapefruit** [Evolution-X/vendor_evolution#39]
Device: Xiaomi Mi 8 (dipper)

ROM: evolution_dipper-ota-td1a.221105.001-11181320-unsigned.zip

Bug description: Roboto font choice text displays in current font instead of Roboto font

How to reproduce:
(1) Go to 'Settings -> The Evolver -> Themes -> Headline / Body font'
(2) Select a font, e.g. Redressed

The Roboto font choice text changes its font to the current font (in this example, Redressed) instead of constantly using the Roboto font. (See screenshot below.)

![Screenshot](https://user-images.githubusercontent.com/119465041/204907626-279a589d-a9db-4df0-a9e7-42644c328d27.png)

I know you think I'm nitpicking (and perhaps I am) but the font choices really ought to remain in their correct fonts.
Someone might choose a font and then scroll down to Roboto and think "Wow! Roboto looks remarkably similar to the font I've just chosen.". It's a small bug, admittedly, but it's a bug nonetheless.

I'm very sorry I did not notice this before posting the similar issue I posted yesterday. I realize that it would have been beneficial to have bundled the two fonts together under the same issue. I've scrolled through the whole list and there are no other fonts which do this so you'll not get another one of these issues from me tomorrow. I promise.

Incidentally, when I select any new font (in 'Settings -> The Evolver -> Themes -> Headline / Body font'), it is not being applied to settings menu headings, just the descriptions. Try any font and you'll see all settings menu headings remain in the default font (like the text "Headline / Body font" in the screenshot above).
Is this intentional or should I create a new issue for this?

Thanks for your attention and for a great ROM.
All your work is most appreciated.

**Comment by Stallix** [comment]
Man, I don't think you're even aware of how font preview works. I get it. It should show Roboto. It STILL shows the proper font when SELECTED. Doesn't matter the preview. Might as well REMOVE ALL FONTS while we're at it. IT ISN'T TOO HARD.

**Comment by Stallix** [comment]
Enjoy Mr. Nitpicker: https://github.com/Evolution-X/vendor_evolution/commit/f029d91ac281595eddeccef75f9eff3efb315900
